script builded
SergeyG22/PrintEnvRepository pull request #5
Opened 2021-12-25 16:53 UTC by SergeyG22

fixes #2

2021-12-25 16:57 UTC, Reeson2003 requested changes

2021-12-25 16:57 UTC, Reeson2003 commented on build.sh
> +g++ main.cpp read_env.cpp read_env.hpp -o printenv
Нужно добавить в readme описание как запускать скрипт

2021-12-25 20:37 UTC, SergeyG22 commented on build.sh
> +g++ main.cpp read_env.cpp read_env.hpp -o printenv
fixed

2021-12-26 17:51 UTC, Reeson2003 requested changes

2021-12-26 17:51 UTC, Reeson2003 commented on README.md
> +Run printenv.
Не сработает. Файл скрипта называется `build.sh`. Я имел в виду, нужно в  readme описать, какой командой запустить скрипт сборки.

2021-12-26 18:12 UTC, SergeyG22 commented on README.md
> +Run printenv.
Исправил.

2021-12-29 06:55 UTC, merged